name: Discussion auto-responder

on:
  discussion:
    types: [created]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  on_discussion_open:
    runs-on: ubuntu-latest
    permissions:
      discussions: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 20.5
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Load Yarn cache
        uses: actions/cache@v3
        id: yarn_cache_id
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - name: Node modules cache
        uses: actions/cache@v3
        id: node_modules_cache_id
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.yarn_cache_id.outputs.cache-hit != 'true' || steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - run: yarn discussion:respond --post ${{ github.event.discussion.body }} --title ${{ github.event.discussion.title }} --number ${{ github.event.discussion.number }} --author ${{ github.event.discussion.author.login }}
